# DevTools
windowrule = float true,match:title ^(Developer Tools)(.*)$
windowrule = float true,match:title ^(DevTools)(.*)$
windowrule = float true,match:class ^(winboat)(.*)$

# Misc
windowrule = float true,match:class ^(kitty)$
windowrule = float true,match:class ^(net.lutris)(.*)$
windowrule = size (monitor_w*0.50) (monitor_h*0.70),move (monitor_w*0.25) (monitor_h*0.15),float true,match:class ^(net.lutris)(.*)$
windowrule = float true,match:class ^(org.telegram)(.*)$